version: '3'
services:
  nginx:
    image: ${IMAGE_NGINX}
    volumes:
      - .:/app # only for local env, remove for prod
      - ./docker/local/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 127.0.0.19:80:80
  rabbit:
    ports:
      - 127.0.0.19:15672:15672
      - 127.0.0.19:5672:5672
    environment: &rabbit_config
      RABBITMQ_HOST: rabbit
      RABBITMQ_PORT: 5672
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
  web:
    user: "1000:1000" # change for another UID in your system
    environment: &project_config
      PHP_ENV: Local
      EMAIL_SERVER: smtp-relay.gmail.com
      EMAIL_PORT: 587
      EMAIL_ENCRYPTION: tls # ssl || tls
      EMAIL_USER: null
      EMAIL_PASSWORD: null
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      <<: *rabbit_config
    volumes:
      - .:/app
      - ./docker/local/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      - ./docker/local/php-override.ini:/usr/local/etc/php/conf.d/php-override.ini:ro
  postgres:
    ports: # only for dev! do not expose this ports in prod mode
      - 127.0.0.19:5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_ROOT_PASSWORD: db_root_password
  queue:
    user: "1000:1000" # change for another UID in your system
    environment: *project_config
    volumes:
      - .:/app
