<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => '',
    'Administrator' => '',
    'Are you sure you want to delete this item?' => '',
    'Check your email for further instructions.' => '',
    'Companies' => '',
    'Company' => '',
    'Company Count' => '',
    'Company is created.' => '',
    'Company is updated.' => '',
    'Company name' => '',
    'Create Company' => '',
    'Create Employee' => '',
    'Create Location' => '',
    'Create User' => '',
    'Creation company administrator:' => '',
    'Creation date' => '',
    'Delete' => '',
    'Email cannot be blank.' => '',
    'Employees' => '',
    'Extra Data' => '',
    'Location is created.' => '',
    'Location is updated.' => '',
    'Locations' => '',
    'Login' => '',
    'Logout' => '',
    'Name' => '',
    'New password saved.' => '',
    'Notification' => '',
    'Owner' => '',
    'Password reset for ' => '',
    'Password reset token cannot be blank.' => '',
    'Passwords must match!' => '',
    'Please choose your new password:' => '',
    'Please fill out the following fields to login:' => '',
    'Please fill out your email. A link to reset password will be sent there.' => '',
    'Request password reset' => '',
    'Reset' => '',
    'Reset password' => '',
    'Restore' => '',
    'Save' => '',
    'Search' => '',
    'Select a company ...' => '',
    'Select administrator...' => '',
    'Select notifications...' => '',
    'Select tariff...' => '',
    'Send' => '',
    'Sorry, we are unable to reset password for the provided email address.' => '',
    'Status' => '',
    'Tariff' => '',
    'The company {company} successfully deleted.' => '',
    'The company {company} successfully restored.' => '',
    'The location {location} successfully deleted.' => '',
    'The location {location} successfully restored.' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update Company: mode' => '',
    'Update Employee: mode' => '',
    'Update Location: {nameAttribute}' => '',
    'Update User: mode' => '',
    'Users' => '',
    'Wrong password reset token.' => '',
    'You want to delete this location. Are you sure?' => '',
];
