<?php
namespace common\ar;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;

/**
 * Class AppActiveRecord
 * @package common\ar
 *
 * @property integer $id
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 *
 */
abstract class AppActiveRecord extends ActiveRecord
{

    const SCENARIO_SEARCH = 'search';
    const SCENARIO_CREATE = 'create';
    const SCENARIO_UPDATE = 'update';

    public function scenarios()
    {
        return parent::scenarios(); // TODO: Change the autogenerated stub
    }

    public function behaviors(): array
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'value' => new Expression('NOW()'),
            ]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'created_at', 'updated_at', 'deleted_at'], 'safe', 'on' => [self::SCENARIO_SEARCH], 'except' => [
                self::SCENARIO_UPDATE,
                self::SCENARIO_CREATE,
            ]],
        ];
    }

    public function attributeLabels(): array
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'deleted_at' => Yii::t('app', 'Deleted At'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

}
